---
title: "Xiaoying Liu"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style>
  h1.title {
    display: none;
  }
  .column-left {
    float: left;
    width: 65%;
    text-align: left;
  }
  .column-right {
    float: right;
    width: 30%;
    text-align: right;
  }
</style>


## Working Papers

&nbsp;

<div style="line-height: 1.5em;">

**Teleworkability: the Weakened Tie between Workplace and Residential Place** [Job Market Paper](files/JMP_XL.pdf)

Abstract: Since the Industrial Revolution, workers have tended to live close to their workplaces due to the need for physical commuting, driving the formation of factory towns and contributing to agglomeration economies. However, advancements in information technology and communication tools have enabled many jobs to be performed remotely. While flexible work arrangements were not widely adopted before 2020, the COVID-19 pandemic accelerated the shift, particularly for teleworkable jobs, granting workers in these roles greater flexibility regarding workplace location. This paper examines the impact of teleworkability on migration patterns, focusing on the likelihood of moving, interstate migration, relocation distances, and the distance between home and workplace. Using data from the American Community Survey (2013–2022) and employing an instrumented difference-in-differences approach, the study reveals that, relative to non-teleworkable workers, teleworkable workers are 6% more likely to migrate overall, experience an 10% increase in interstate migration, and move an average of 24 miles farther. The analysis also shows that teleworkable workers are more willing to accept longer commutes and live farther from their workplaces, reflecting a weakened link between home and office locations. These effects are particularly pronounced among women, married couples, and dual-career households. Furthermore, county-pair analysis demonstrates a notable shift in migration preferences, with workers moving out of counties with higher shares of teleworkable workers and larger population. This study underscores the significant implications of telework for individual lifestyle choices and broader economic and urban structures, offering valuable insights for policymakers and urban planners navigating the post-pandemic labor market.

&nbsp;

**Higher Education Expansion and Intergenerational Mobility**

Abstract: This paper tentatively proposes a human capital investment model to analyze how higher education expansion has changed education attainment of children. The model assumes altruistic parents who invest in children’s schooling and non-schooling activities. Schooling investment has an upper limit while non-schooling investment does not. When higher education expansion takes place, meaning that participation rate of higher education is raised and the probability of being admitted to colleges increases, parents would adjust their investment behavior to maximize dynastic utility. Model implies that education expansion is not necessarily associated with an improvement in intergenerational mobility since rich families having more resources would invest more in non-schooling activities when schooling investment is constrained. Using data from 2010 Chinese Family Panel Studies (CFPS) to estimate the effects of the expansion on intergenerational mobility (IGM), results show an improvement in IGM using child’s overall education attainment as the measure but no significant increase in child’s probability of being admitted to higher education institutions. Further study indicates that richer and higher-educated families spend more in child’s extracurricular activities as education expansion happens.

<!---
**Are Businesses Doing Business in China? with Ruochen Dai, Shuo Liu, Xiaobo Zhang**

How many firms shown in the Business Registration Database are doing business in the economy? According to our estimation, nearly 40 percent of registered firms in China are probably not. We define these companies as inactive firms. Seemingly harmless, inactive firms may have a great impact on the economy. Shell companies, lowering the operating cost of some companies through financial maneuvers, could potentially squeeze out other businesses. Closed firms may affect the economy from the policy side. Firm registration database is widely used to measure productive activity and gauge the size of entrepreneurship, which are crucial for both economic analysis and policy making. The extensive existence of inactive firms could bias the policy decision and thus affect the economy as a whole.

Given the importance of inactive firms, the studies on this topic are scarce in large due to lack of data. In this paper, based on the primarily collected Enterprise Survey for Innovation and Entrepreneurship in China (ESIEC) data and the administrative annual enterprise report data, we successfully label the business status of a representative sample of all registered companies in China. Then, we construct an ensemble learning model, the Gradient Boosting Decision Trees (GBDT) to detect the inactive companies. Results show that for all existed firms in administrative record in 2018, around 40 percent are inactive. The share of inactive firms varies across industries and locations. Inactive firms concentrate in Liaoning and Henan province and comprise a smaller fraction in Zhejiang province. They also concentrate in high-subsidy industries such as agriculture, and value-added tax reform industries such as transportation, finance, and business service industries. Using public data, we construct an XGBoost model to predict the inactive status of companies. XGBoost behaves well in spotting inactive firms, with a precision rate being 0.71 and sensitivity rate being 0.65.
--->

&nbsp;

---

## Publication

&nbsp;

**[Measuring the Quality of a Match](https://doi.org/10.1016/j.labeco.2024.102568), with Michele Belot and Vaios Triantafyllou**

*Labour Economics*, 2024

Abstract: The quality of an employment match is a central concept in labor economics. It is relevant for evaluating the welfare impact of labor market policies, and for our understanding of labor market dynamics. This paper reviews the challenges associated with measuring match quality. We first review measures commonly used in the literature, their advantages, and drawbacks. We then present novel evidence from a survey sample of US employees where alternative measures were collected simultaneously. We show that while some of these measures correlate well, others do not. Finally, we present additional partial evidence on the correlations between measures based on the National Longitudinal Survey of Youth (NLSY79), a substantially larger and nationally representative survey. The takeaway message is a word of caution regarding the interpretation of some of these measures and specific concerns regarding using wages and tenure as indicators of match quality.

&nbsp;

---

## Work in Progress

&nbsp;

**Passion at Work, with Michele Belot and Vaios Triantafyllou**

</div>
